import Footer from "@/components/Footer";
import "./globals.css";

import NavBar from "@/components/global/nav-bar/NavBar";
import ToastConfig from "@/config/toastConfig";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={``}>
        <ToastConfig/>
        <NavBar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
