import Footer from "@/components/Footer";
import "./globals.css";

import NavBar from "@/components/global/nav-bar/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
  
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
